### ISSUE TITLE
cwl-metrics to capture metrics for steps that are not using containers?

### ISSUE THREAD

**Issue by MichaelTong** [inutano/cwl-metrics#1]
Hi,

Thank you for your hard work to make this happen.

I'm just wondering if cwl-metrics is able to capture metrics for steps that are not using containers?

Thanks again.

**Comment by inutano** [comment]
Hi @MichaelTong! The answer is unfortunately no: CWL-metrics is using Telegraf docker input plugin to make it easier to isolate the metrics of tool executions from those of the host system. Do you have a situation that you can't use containers? If there's a use case, we will consider to implement the function.

**Comment by MichaelTong** [comment]
We just have a few steps using command line tools, but they are not heavy steps, so I think it's fine not to capture outside of containers.

**Comment by inutano** [comment]
The current implementation might work with a workflow which contains both native and container steps, and the output data just won't have runtime metrics data for native steps. Let me know if you had a problem on such workflow runs!
