### ISSUE TITLE
cwltool wrapper

### ISSUE THREAD

**Issue by KerstenBreuer** [inutano/cwl-metrics#10]
Hi,

I am searching for an option to collect metadata directly upon calling cwltool. Is this what your script https://github.com/inutano/cwl-metrics/blob/master/bin/cwltool does?

If so could you give some help on how to use it?

Thank you

**Comment by inutano** [comment]
The usage section of the documentation [here](https://inutano.github.io/cwl-metrics/) describes the options you need to specify with cwltool when you collect the runtime metrics with cwl-metrics. The script is just a wrapper to do the same thing, so you can use it, but you don't have to.
