### ISSUE TITLE
failure in cwl-metrics fetch

### ISSUE THREAD

**Issue by ifishlin** [inutano/cwl-metrics#11]
I tried the cwl-metrics and the installation seems no probelm. But I always had this failure when fetching. Any clues? My OS is centos 8. thanks

<pre><code>
(base) [yuyulin@benchmark-cwl ~]$ .cwlmetrics/bin/cwl-metrics start
Starting CWL-metrics...
Creating Elasticsearch index...
{"telegraf":{"aliases":{},"mappings":{"docker_metrics":{"properties":{"timestamp":{"type":"date","format":"epoch_second"}}}},"settings":{"index":{"creation_date":"1604351476893","number_of_shards":"5","number_of_replicas":"1","uuid":"UbAwn2W6S8qq4wKlf2ug6w","version":{"created":"6020299"},"provided_name":"telegraf"}}}}
{"workflow":{"aliases":{},"mappings":{"workflow_log":{"properties":{"workflow":{"properties":{"end_date":{"type":"date","format":"yyyy-MM-dd HH:mm:ss"},"start_date":{"type":"date","format":"yyyy-MM-dd HH:mm:ss"}}}}}},"settings":{"index":{"mapping":{"total_fields":{"limit":"5000"}},"number_of_shards":"5","provided_name":"workflow","creation_date":"1604351477243","number_of_replicas":"1","uuid":"7lqUjfqDR-2cfOAmVvwKOw","version":{"created":"6020299"}}}}}

CWL-metrics is running.

(base) [yuyulin@benchmark-cwl ~]$ .cwlmetrics/bin/cwl-metrics fetch tsv
Traceback (most recent call last):
	8: from /cwl-metrics-client/lib/client.rb:19:in `<main>'
	7: from /cwl-metrics-client/lib/cwl-metrics/cwl-metrics.rb:23:in `tsv'
	6: from /cwl-metrics-client/lib/cwl-metrics/cwl-metrics.rb:103:in `metrics'
	5: from /cwl-metrics-client/lib/cwl-metrics/cwl-metrics.rb:117:in `fetch_metrics'
	4: from /usr/local/bundle/gems/elasticsearch-api-6.0.2/lib/elasticsearch/api/actions/search.rb:187:in `search'
	3: from /usr/local/bundle/gems/elasticsearch-transport-6.0.2/lib/elasticsearch/transport/client.rb:131:in `perform_request'
	2: from /usr/local/bundle/gems/elasticsearch-transport-6.0.2/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
	1: from /usr/local/bundle/gems/elasticsearch-transport-6.0.2/lib/elasticsearch/transport/transport/base.rb:323:in `perform_request'
/usr/local/bundle/gems/elasticsearch-transport-6.0.2/lib/elasticsearch/transport/transport/base.rb:205:in `__raise_transport_error': [400] {"error":{"root_cause":[{"type":"parsing_exception","reason":"[terms] failed to parse field [size]","line":1,"col":315}],"type":"parsing_exception","reason":"[terms] failed to parse field [size]","line":1,"col":315,"caused_by":{"type":"illegal_argument_exception","reason":"[size] must be greater than 0. Found [0] in [summary_per_container_id]"}},"status":400} (Elasticsearch::Transport::Transport::Errors::BadRequest)
</code></pre>

**Comment by inutano** [comment]
Hi @ifishlin, thanks for trying! It means that the store does not have any metrics data. You need to run a CWL workflow via cwltool with specified options as described [here](https://inutano.github.io/cwl-metrics/#usage). Let me know if you need more help!

**Comment by sagnikbanerjee15** [comment]
Hello,

I am getting the exact same error even when I have executed a command via cwltool. Could you please help?

```
cwl-metrics run /work/CWL_and_docker/CWL_scripts/tools/samtools/1.14/samtools-view.cwl --help
./cwl-metrics/cwl-metrics fetch
Traceback (most recent call last):
	9: from /app/lib/client.rb:17:in `<main>'
	8: from /app/lib/cwl-metrics/cwl-metrics.rb:18:in `json'
	7: from /app/lib/cwl-metrics/cwl-metrics.rb:103:in `metrics'
	6: from /app/lib/cwl-metrics/cwl-metrics.rb:117:in `fetch_metrics_records'
	5: from /app/lib/cwl-metrics/cwl-metrics.rb:185:in `fetch_metrics'
	4: from /usr/local/bundle/gems/elasticsearch-api-7.10.0/lib/elasticsearch/api/actions/search.rb:103:in `search'
	3: from /usr/local/bundle/gems/elasticsearch-transport-7.10.0/lib/elasticsearch/transport/client.rb:176:in `perform_request'
	2: from /usr/local/bundle/gems/elasticsearch-transport-7.10.0/lib/elasticsearch/transport/transport/http/faraday.rb:37:in `perform_request'
	1: from /usr/local/bundle/gems/elasticsearch-transport-7.10.0/lib/elasticsearch/transport/transport/base.rb:347:in `perform_request'
/usr/local/bundle/gems/elasticsearch-transport-7.10.0/lib/elasticsearch/transport/transport/base.rb:218:in `__raise_transport_error': [400] {"error":{"root_cause":[{"type":"x_content_parse_exception","reason":"[1:315] [terms] failed to parse field [size]"}],"type":"x_content_parse_exception","reason":"[1:315] [terms] failed to parse field [size]","caused_by":{"type":"illegal_argument_exception","reason":"[size] must be greater than 0. Found [0] in [summary_per_container_id]"}},"status":400} (Elasticsearch::Transport::Transport::Errors::BadRequest)
```

Thanks.

**Comment by inutano** [comment]
Hi @sagnikbanerjee15, thanks for trying! It looks like your `samtools view -h` quits very shortly, which means its docker container ups and downs less than a second, thus the metrics collection program (telegraf) could not collect the metrics. Therefore, `fetch` command could not find any stored metrics, and outputs the error message. (the message should be improved to explain the situation though) Please try with a command with real input data which takes more than 10 seconds. Let me know if you got any further question!
