### ISSUE TITLE
Permission Error 

### ISSUE THREAD

**Issue by skanwal** [inutano/cwl-metrics#4]
Hi Inutano,

Thanks for the great software.
Excited to be the first ever individual opening an issue under this repo :)

I am trying to test `cwl-metrics` using simple kallisto's CWL CommandlineTool implementation.

The command I am using is:
```
cwltool --debug --leave-container --timestamps --compute-checksum --record-container-id --cidfile-dir $(pwd)/result --outdir $pwd/result kallisto-quant.cwl kallisto-quant.json 2> $(pwd)/result/cwltool.log
```

I am attaching the `cwltool.log` file, which gets created under `result` directory, for the error reference.
Would acknowledge if you can help resolve this issue. 

[cwltool.log](https://github.com/inutano/cwl-metrics/files/2221479/cwltool.log)

**Comment by tom-tan** [comment]
It is because you specified wrong value for `--outdir`.
Use `--outdir $(pwd)/result` instead of `--outdir $pwd/result`.

**Comment by skanwal** [comment]
D'oh.. That's a bummer.
Thanks for your prompt reply.

**Comment by inutano** [comment]
Hi Sehrish, thanks for trying out this! I think @tom-tan's suggest would solve your problem so I'm closing this issue, but let me know if you had any other problems!
