### ISSUE TITLE
pypi package

### ISSUE THREAD

**Issue by KerstenBreuer** [inutano/cwl-metrics#7]
Hi,

would it be possible to get a package in pypi?

Thank you

**Comment by inutano** [comment]
Hi, unfortunately no. We wanted cwl-metrics not to be dependent on a programming language so that users can easily install it. You can use `curl "https://raw.githubusercontent.com/inutano/cwl-metrics/master/bin/cwl-metrics" | bash` as described [here](https://inutano.github.io/cwl-metrics/).
