### ISSUE TITLE
singularity instead of docker

### ISSUE THREAD

**Issue by KerstenBreuer** [inutano/cwl-metrics#8]
Hi,

you are listing docker as prerequisite of your tool. Would it be possible to replace it with singularity?

Thank you

**Comment by inutano** [comment]
This is actually what we want to achieve, but currently not. The problem is that we cannot bind a running singularity process and a step in a workflow that is done by using container-id for Docker containers. We need to find a way to do it.

**Comment by KerstenBreuer** [comment]
OK thanks. So we will use docker for now where applicable.
