### ISSUE TITLE
record I/O

### ISSUE THREAD

**Issue by KerstenBreuer** [inutano/cwl-metrics#9]
Hi,

Does the package record byte read and written from/to the file system? This would be extremely useful to have as many bioinformatic analysis or processing steps are I/O limited.

Thank you

**Comment by inutano** [comment]
Yes, cwl-metrics records total block I/O of the workflow. You can see an example in cell number 40 of our jupyter notebook [here](https://nbviewer.jupyter.org/github/inutano/cwl-metrics-manuscript/blob/master/notebook/CWL-metrics%20runtime%20metrics%20analysis.ipynb).

**Comment by KerstenBreuer** [comment]
Perfect. Thank you. Seems like exactly what we needed.

**Comment by inutano** [comment]
Let me know if you need any further assistance!
